[package]
name = "fuzzy_matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1.50"
cxx-build = "1.0.123"

[dependencies]
cc = "1.0.99"
cxx = "1.0.123"